remove build.sh

diff --git a/.github/workflows/build-macos.yml b/.github/workflows/build-macos.yml
--- a/.github/workflows/build-macos.yml
+++ b/.github/workflows/build-macos.yml
@@ -96,11 +96,104 @@ jobs:
         export PATH="/usr/local/opt/qt@5/bin:${PATH}"
         which qmake
         pipenv run pyqtdeploy-sysroot --target macos-64 --verbose sysroot/sysroot.toml
-  
-    - name: Build app
+        
+    - name: Write build config
+      run: |
+        pipenv run python bin/update_build_info.py
+
+    - name: Write build config
+      run: |
+        pipenv run . ./bin/setup_provisioning_profile.sh
+
+    - name: Generate qmake project
       run: |
         export PATH="`pwd`/sysroot/sysroot-macos-64/Qt/bin:${PATH}"
-        pipenv run bin/build.sh
+      	pipenv run pyqtdeploy-build --verbose  --resources 12 --target macos-64 --build-dir build/osx familydiagram.pdt
+
+    - name: Generate qmake project
+      run: |
+        export PATH="`pwd`/sysroot/sysroot-macos-64/Qt/bin:${PATH}"
+        cd build/osx
+        qmake -spec macx-xcode CONFIG+=no_autoqmake CONFIG+=debug CONFIG-=release CONFIG+=beta
+        echo "Updating xcode project to new build system"
+        python3 bin/fixup_xcodeproj_workspace.py
+
+    - name: Qt Preprocess
+      run: |
+        xcodebuild \
+          -project build/osx/Family\ Diagram.xcodeproj \
+          -target "Qt Preprocess" \
+          -configuration Release
+
+    - name: Build App
+      run: |
+        xcodebuild \
+          -project build/osx/Family\ Diagram.xcodeproj \
+          -scheme "Family Diagram" \
+          -configuration Release \
+          -archivePath ${FD_BUILD_DIR}/Family\ Diagram.xcarchive \
+          OTHER_CODE_SIGN_FLAGS="--keychain ${FD_BUILD_KEYCHAIN_NAME}" \
+          archive
+
+    - name: Export archive
+      run: |
+        xcodebuild \
+          -verbose \
+          -exportArchive \
+          -archivePath ${FD_BUILD_DIR}/Family\ Diagram.xcarchive \
+          -exportOptionsPlist build/osx/ExportOptions.plist \
+          -exportPath $FD_BUILD_DIR/Export
+
+    - name: Prep App Bundle
+        rm build/osx/Release/Family\ Diagram.app
+        cp -R $FD_BUILD_DIR/Export/Family\ Diagram.app build/osx/Release
+        ditto -c -k --keepParent \
+            "$FD_BUILD_DIR/Family Diagram.app" \
+            "$FD_BUILD_DIR/Family Diagram.zip"
+
+    - name: Uploading for notarization
+      run: |
+        xcrun notarytool submit \
+          --key "${FD_BUILD_AC_AUTH_KEY_FPATH}" \
+          --key-id "${FD_BUILD_AC_AUTH_KEY_ID}" \
+          --issuer "${FD_BUILD_AC_AUTH_KEY_ISSUER}" \
+          --timeout 2h \
+          --wait --progress \
+          --output-format plist \
+          "$FD_BUILD_DIR/Family Diagram.zip" \
+          > ${FD_BUILD_DIR}/NotaryResults.plist || true
+        
+        REQUEST_STATUS=$(/usr/libexec/PlistBuddy -c "Print :status" build/osx/Release/NotaryResults.plist)
+        if [ "$REQUEST_STATUS" != "Accepted" ]; then
+            REQUEST_UUID=$(/usr/libexec/PlistBuddy -c "Print :id" ${FD_BUILD_DIR}/NotaryResults.plist)
+            echo "PKS *** Notarizing failed, fetching developer log for Request ID: ${REQUEST_UUID}..."
+            xcrun notarytool log $REQUEST_UUID \
+                --key "${FD_BUILD_AC_AUTH_KEY_FPATH}" \
+                --key-id "${FD_BUILD_AC_AUTH_KEY_ID}" \
+                --issuer "${FD_BUILD_AC_AUTH_KEY_ISSUER}" 
+            exit 1
+        fi
+
+    - name: Stapling app bundle
+      run: |
+        xcrun stapler staple "${FD_BUILD_DIR}/Family Diagram.app"
+
+    - name: Create DMG
+      run: |
+        cd build/osx
+        create-dmg \
+          --volname "Family Diagram" \
+          --volicon "PKDiagram-Filled.icns" \
+          --background "DMG-Background.png" \
+          --window-pos 200 200 \
+          --window-size 800 600 \
+          --icon-size 128 \
+          --icon "Family Diagram.app" 200 350 \
+          --hide-extension "Family Diagram.app" \
+          --app-drop-link 600 350 \
+          --no-internet-enable \
+          "Release/Family Diagram.dmg" \
+          "Release/"
 
     - name: Verify app
       run: |
