consolidate into one workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,22 +1,367 @@
-name: Upload Release Artifacts
+name: Release
 
 on:
-  workflow_run:
-    workflows: 
-      - "Build macOS"
-      - "Build Windows"
-    types:
-      - completed
+  push:
+    branches:
+      - master
+  workflow_dispatch:
+
+env:
+  TWINE_REPOSITORY_URL: "${{ secrets.TWINE_REPOSITORY_URL }}"
+  TWINE_USERNAME: "${{ secrets.TWINE_USERNAME }}"
+  TWINE_PASSWORD: "${{ secrets.TWINE_PASSWORD }}"
+  FD_BUILD_DIR: ${{ github.workspace }}/build/osx/Release
+  FD_BUILD_KEYCHAIN_NAME: ${{ github.workspace }}/build/osx/Release/build.keychain-db
+  FD_BUILD_PROVISIONING_PROFILE_FPATH: ${{ github.workspace }}/build/osx/Release/FD.provisionprofile
+  FD_BUILD_CERTIFICATE_FPATH: ${{ github.workspace }}/build/osx/Release/FD_certificate.crt
+  FD_BUILD_PRIVATE_KEY_FPATH: ${{ github.workspace }}/build/osx/Release/FD_certificate.pem
+  FD_BUILD_AC_AUTH_KEY_FPATH: ${{ github.workspace }}/build/osx/Release/AuthKey_${{ secrets.FD_BUILD_AC_AUTH_KEY_ID }}.p8
+  FD_APP_PATH: ${{ github.workspace }}/build/osx/Release/Family\ Diagram.app
+  FD_BUILD_APPLE_ID: "${{ secrets.FD_BUILD_APPLE_ID }}"
+  FD_BUILD_APPLE_ID_PASSWORD: "${{ secrets.FD_BUILD_APPLE_ID_PASSWORD }}"
+  FD_BUILD_PROVISIONING_PROFILE_BASE64: "${{ secrets.FD_BUILD_PROVISIONING_PROFILE_BASE64 }}"
+  FD_BUILD_CERTIFICATE_BASE64: "${{ secrets.FD_BUILD_CERTIFICATE_BASE64 }}"
+  FD_BUILD_PRIVATE_KEY_BASE64: "${{ secrets.FD_BUILD_PRIVATE_KEY_BASE64 }}"
+  FD_BUILD_CERTIFICATE_PASSWORD: "${{ secrets.FD_BUILD_CERTIFICATE_PASSWORD }}"
+  FD_BUILD_AC_AUTH_KEY_ID: "${{ secrets.FD_BUILD_AC_AUTH_KEY_ID }}"
+  FD_BUILD_AC_AUTH_KEY_BASE64: "${{ secrets.FD_BUILD_AC_AUTH_KEY_BASE64 }}"
+  FD_BUILD_AC_AUTH_KEY_ISSUER: "${{ secrets.FD_BUILD_AC_AUTH_KEY_ISSUER }}"
+  FD_BUILD_PEPPER: "${{ secrets.FD_BUILD_PEPPER }}"
+  FD_BUILD_BUGSNAG_API_KEY: "${{ secrets.FD_BUILD_BUGSNAG_API_KEY }}"
 
 jobs:
-  upload-release:
+
+  setup:
     runs-on: ubuntu-latest
+    steps:
+
+    - name: Get Version
+      id: get-version
+      run: |
+        echo "version=`python -c "import sys; sys.path.insert(0, './pkdiagram'); import version; print(version.VERSION)"`" >> $GITHUB_OUTPUT
+
+  check-setup:
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+    - name: Echo version
+      run: |
+        echo "Got version: ${{ needs.setup.outputs.version }}"
+        if [ -z "${{ needs.setup.outputs.version }}" ]; then
+          echo "Version not set"
+          exit 1
+        fi
+
+  build-osx:
+    # x86 w/ python-3.12.5
+    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
+    runs-on: macos-12
+    needs: setup
 
     steps:
-    - name: Get Version
+
+    - uses: actions/checkout@v4
+      with:
+        submodules: true
+
+    # # Will provide an SSH command in the logs that you can use to access the runner.
+    # - name: Setup tmate session
+    #   uses: mxschmitt/action-tmate@v3        
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.10.4
+        # cache: 'pipenv'
+
+    - run: |
+        pip install pipenv
+        mkdir .venv
+        rm Pipfile.lock
+        pipenv --clear
+        pipenv install --dev  --skip-lock --verbose
+
+    # It is faster to install homebrew than to restore from cache
+    - name: brew install qt@5 create-dmg
       run: |
-        echo "version=`pipenv run python -c "import sys; sys.path.insert(0, './pkdiagram'); import version; print(version.VERSION)"`" >> $GITHUB_ENV
-        echo $version
+        brew install qt@5 create-dmg
+
+    ## App
+    
+    - name: Setup _pkdiagram caching
+      id: cache-_pkdiagram
+      uses: actions/cache@v2
+      with:
+        path: |
+          pkdiagram/_pkdiagram/build
+        key: _pkdiagram-${{ runner.os }}-${{ hashFiles('./pkdiagram/_pkdiagram/sip/*.sip', './pkdiagram/_pkdiagram/*.h', './pkdiagram/_pkdiagram/*.cpp') }}
+    
+    - name: sip-build for _pkdiagram
+      if: steps.cache-_pkdiagram.outputs.cache-hit != 'true'
+      run: |
+        export PATH="/usr/local/opt/qt@5/bin:${PATH}"
+        which qmake
+        cd pkdiagram/_pkdiagram
+        pipenv run sip-build --no-compile
+        moc -o build/_pkdiagram/moc_unsafearea.cpp unsafearea.h
+        moc -o build/_pkdiagram/moc__pkdiagram.cpp _pkdiagram.h
+
+    - name: Download zlib source
+      run: |
+        wget -L "https://www.zlib.net/fossils/zlib-1.2.11.tar.gz" -P ./sysroot/
+
+    - name: Setup sysroot caching
+      id: cache-sysroot
+      uses: actions/cache@v2
+      with:
+        path: ./sysroot/sysroot-macos-64
+        key: sysroot-macOS
+        # key: sysroot-${{ runner.os }}-${{ hashFiles('./sysroot/sysroot.toml') }}
+
+    - name: Build sysroot
+      if: steps.cache-sysroot.outputs.cache-hit != 'true'
+      run: |
+        export PATH="/usr/local/opt/qt@5/bin:${PATH}"
+        pipenv run pyqtdeploy-sysroot --target macos-64 --verbose sysroot/sysroot.toml
+
+    - uses: actions/cache/save@v3
+      if: steps.cache-sysroot.outputs.cache-hit != 'true'
+      with:
+        path: ./sysroot/sysroot-macos-64
+        key: sysroot-macOS
+
+    - name: Write build config
+      run: |
+        export PATH="`pwd`/sysroot/sysroot-macos-64/Qt/bin:${PATH}"
+        pipenv run pyqtdeploy-build --verbose  --resources 12 --target macos-64 --build-dir build/osx familydiagram.pdt
+        rsync -avzq build/common-config/* build/osx
+        rsync -avzq build/osx-config/* build/osx
+        pipenv run python bin/update_build_info.py
+
+    - name: qmake
+      run: |
+        export PATH="`pwd`/sysroot/sysroot-macos-64/Qt/bin:${PATH}"
+        cd build/osx
+        qmake -spec macx-xcode CONFIG+=no_autoqmake CONFIG+=debug CONFIG-=release CONFIG+=beta
+
+    - name: Setup provisioning profile
+      run: |
+        pipenv run ./bin/setup_provisioning_profile.sh
+
+    - name: Update xcode project to new build system
+      run: |
+        python3 bin/fixup_xcodeproj_workspace.py
+
+    - name: Qt Preprocess
+      run: |
+        xcodebuild \
+          -project build/osx/Family\ Diagram.xcodeproj \
+          -target "Qt Preprocess" \
+          -configuration Release
+
+    - name: Build App
+      run: |
+        pipenv run xcodebuild \
+          -project build/osx/Family\ Diagram.xcodeproj \
+          -scheme "Family Diagram" \
+          -configuration Release \
+          -archivePath ${FD_BUILD_DIR}/Family\ Diagram.xcarchive \
+          -xcconfig build/osx/Family-Diagram-Release.xcconfig \
+          archive
+
+    - name: Export archive
+      run: |
+        xcodebuild \
+          -verbose \
+          -exportArchive \
+          -archivePath ${FD_BUILD_DIR}/Family\ Diagram.xcarchive \
+          -exportOptionsPlist build/osx/ExportOptions.plist \
+          -exportPath $FD_BUILD_DIR/Export
+
+    - name: Verify app
+      run: |
+        build/osx/Release/Export/Family\ Diagram.app/Contents/MacOS/Family\ Diagram --version
+
+    - name: Prep App Bundle
+      run: |
+        rm build/osx/Release/Family\ Diagram.app # symlink
+        cp -R $FD_BUILD_DIR/Export/Family\ Diagram.app build/osx/Release
+        ditto -c -k --keepParent \
+            "$FD_BUILD_DIR/Family Diagram.app" \
+            "$FD_BUILD_DIR/Family Diagram.zip"
+
+    - name: Uploading for notarization
+      run: |
+        xcrun notarytool submit \
+          --key "${FD_BUILD_AC_AUTH_KEY_FPATH}" \
+          --key-id "${FD_BUILD_AC_AUTH_KEY_ID}" \
+          --issuer "${FD_BUILD_AC_AUTH_KEY_ISSUER}" \
+          --timeout 2h \
+          --wait --progress \
+          --output-format plist \
+          "$FD_BUILD_DIR/Family Diagram.zip" \
+          > ${FD_BUILD_DIR}/NotaryResults.plist || true
+        
+        REQUEST_STATUS=$(/usr/libexec/PlistBuddy -c "Print :status" build/osx/Release/NotaryResults.plist)
+        if [ "$REQUEST_STATUS" != "Accepted" ]; then
+            REQUEST_UUID=$(/usr/libexec/PlistBuddy -c "Print :id" ${FD_BUILD_DIR}/NotaryResults.plist)
+            echo "PKS *** Notarizing failed, fetching developer log for Request ID: ${REQUEST_UUID}..."
+            xcrun notarytool log $REQUEST_UUID \
+                --key "${FD_BUILD_AC_AUTH_KEY_FPATH}" \
+                --key-id "${FD_BUILD_AC_AUTH_KEY_ID}" \
+                --issuer "${FD_BUILD_AC_AUTH_KEY_ISSUER}" 
+            exit 1
+        fi
+
+    - name: Stapling app bundle
+      run: |
+        xcrun stapler staple "${FD_BUILD_DIR}/Family Diagram.app"
+
+    - name: Create DMG
+      run: |
+        cd build/osx
+        create-dmg \
+          --volname "Family Diagram" \
+          --volicon "PKDiagram-Filled.icns" \
+          --background "DMG-Background.png" \
+          --window-pos 200 200 \
+          --window-size 800 600 \
+          --icon-size 128 \
+          --icon "Family Diagram.app" 200 350 \
+          --hide-extension "Family Diagram.app" \
+          --app-drop-link 600 350 \
+          --no-internet-enable \
+          "Release/Family Diagram.dmg" \
+          "Release/"
+
+    - name: Upload Artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: familydiagram-macos
+        path: build/osx/Release/Family Diagram.dmg
+
+  build-windows:
+    runs-on: windows-2019
+    needs: setup
+  
+    steps:
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+  
+      - name: Set up Python 3.10.4
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.10.4
+          # cache: 'pipenv'
+      - run: |
+          pip install pipenv
+          mkdir .venv
+          # rm Pipfile.lock
+          pipenv --clear
+          pipenv install --dev --skip-lock --verbose
+  
+      - name: pipenv install aqtinstall
+        run: pipenv install aqtinstall
+  
+      - name: Install Qt
+        run: |
+          pipenv run aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir C:\Qt --archives qtbase qtdeclarative qtgraphicaleffects qtimageformats qtquickcontrols qtquickcontrols2 qttools qtwinextras
+        
+      - name: Setup _pkdiagram caching
+        id: cache-_pkdiagram
+        uses: actions/cache@v2
+        with:
+          path: |
+            pkdiagram/_pkdiagram/build
+          key: _pkdiagram-${{ runner.os }}-${{ hashFiles('./pkdiagram/_pkdiagram/sip/*.sip', './pkdiagram/_pkdiagram/*.h', './pkdiagram/_pkdiagram/*.cpp') }}
+      
+      - name: sip-build for _pkdiagram
+        if: steps.cache-_pkdiagram.outputs.cache-hit != 'true'
+        run: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+          set PATH=C:\Qt\5.15.2\msvc2019_64\bin;%PATH%
+          qmake --version
+          cd pkdiagram\_pkdiagram
+          pipenv run sip-build --no-compile
+          moc -o build\_pkdiagram\moc_unsafearea.cpp unsafearea.h
+          moc -o build\_pkdiagram\moc__pkdiagram.cpp _pkdiagram.h
+        shell: cmd
+  
+      - name: Setup sysroot caching
+        id: cache-sysroot
+        uses: actions/cache@v2
+        with:
+          path: sysroot/sysroot-win-64
+          key: sysroot-win-64
+          # key: sysroot-${{ runner.os }}-${{ hashFiles('./sysroot/sysroot.toml') }}
+  
+      - name: Build sysroot
+        if: steps.cache-sysroot.outputs.cache-hit != 'true'
+        run: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+          set PATH=C:\Qt\5.15.2\msvc2019_64\bin;%PATH%
+          cd pkdiagram\_pkdiagram
+          dir build\_pkdiagram\release
+          mkdir build\_pkdiagram\release
+          moc -o build\_pkdiagram\release\moc_unsafearea.cpp unsafearea.h
+          moc -o build\_pkdiagram\release\moc__pkdiagram.cpp _pkdiagram.h
+          cd ..\..
+          pipenv run pyqtdeploy-sysroot --verbose sysroot/sysroot.toml
+        shell: cmd
+  
+      - uses: actions/cache/save@v3
+        if: steps.cache-sysroot.outputs.cache-hit != 'true'
+        with:
+          path: sysroot/sysroot-win-64
+          key: sysroot-win-64
+  
+      - name: Write build config
+        run: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+          pipenv run python bin\update_build_info.py
+        shell: cmd
+  
+      - name: pyqtdeploy-build
+        run: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+          set PYTHONPATH=%cd%\lib\site-packages
+          pipenv run pyqtdeploy-build --verbose --resources 12 --build-dir build\\win32 --target win-64 familydiagram.pdt
+          copy build\common-config\* build\win32\
+          copy build\win32-config\* build\win32\
+        shell: cmd
+  
+      - name: qmake
+        run: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+          set PATH=%cd%\sysroot\sysroot-win-64\Qt\bin;%PATH%
+          cd build\win32
+          qmake -tp vc "CONFIG-=debug" "CONFIG+=release" "CONFIG+=beta"
+        shell: cmd # has to be shell or qmake won't work
+  
+      - name: Build
+        run: |
+          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+          echo on
+          cd build\win32
+          msbuild /p:Configuration=Release "Family Diagram.vcxproj"
+        shell: cmd
+  
+      - name: Zip build
+        run: |
+          7z a -tzip "build\win32\Release\Family Diagram.zip" "build\win32\Release\Family Diagram.exe"
+        shell: cmd
+          
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: familydiagram-windows
+          path: build\win32\Release\Family Diagram.zip
+  
+  publish:    
+    runs-on: ubuntu-latest
+    needs: [build-osx, build-windows]
+    steps:
 
     - uses: actions/download-artifact@v2
 
@@ -26,8 +371,8 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        tag_name: ${{ env.version }}
-        release_name: ${{ env.version }}
+        tag_name: ${{ needs.jobs.setup.get-version.version }}
+        release_name: ${{ needs.jobs.setup.get-version.version }}
         draft: false
         prerelease: false
 
@@ -38,7 +383,7 @@ jobs:
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: Family Diagram.dmg
-        asset_name: Family Diagram ${{ env.version }}.dmg
+        asset_name: Family Diagram ${{ needs.jobs.setup.get-version.version }}.dmg
         asset_content_type: application/x-apple-diskimage
 
     - name: Upload Windows Build
@@ -48,5 +393,29 @@ jobs:
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: Family Diagram.zip
-        asset_name: Family Diagram ${{ env.version }}.zip
-        asset_content_type: application/vnd.microsoft.portable-executable
+        asset_name: Family Diagram ${{ needs.jobs.setup.get-version.version }}.zip
+        asset_content_type: application/zip
+
+  update-appcast:
+    runs-on: ubuntu-latest
+    needs: publish
+    steps:
+
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Generate appcast.xml
+        id: get_release
+        run: |
+            python bin/github_releases_2_appcast.py
+
+      - name: Push appcast.xml to familydiagram.com/appcast.xml
+        env:
+            FAMILYDIAGRAM_COM_SSH_PRIVATE_KEY: ${{ secrets.FAMILYDIAGRAM_COM_SSH_PRIVATE_KEY }}
+        run: |
+            echo "${FAMILYDIAGRAM_COM_SSH_PRIVATE_KEY}" > private_key
+            chmod 600 private_key
+            mkdir -p ~/.ssh
+            ssh-keyscan -H familydiagram.com >> ~/.ssh/known_hosts
+            scp -i private_key appcast.xml patrick@familydiagram.com:/var/www/html/appcast.xml
+            rm private_key
